This is a collection of tips on how to avoid using products from big tech companies residing in areas without a properly functioning democracy.
<<top>>
#+OPTIONS: toc:nil
#+TOC: headlines 3


* Export this document :noexport:

M-x org-md-export-to-markdown RET <filename> RET


* Strategies :noexport:

** Extend the life of existing hardware

** Recycle hardware as much as possible

Buy refurbished device.
Optimize the use of the device to minimize the usage of bad software and/or services.

*Example*
Buy a refurbished iPad.
Replace the usage of bad stuff like GMail, Google Drive, Google Photos etc.


** Buy hardware from good sources

*Example*
The FairPhone is mainstream, buy it at a local shop (DK: Proshop).
It's Stock Android, but as always you can replace as much of the Google stuff as you are comfortable with.


** All in - pure hardware and software
As you'd expect, this can be tricky.

*Example*
You like the FairPhone, but you want to get rid of the Google spyware.
Look at Murena.com - they offer the FairPhone with Android replaced by /e/OS (a system that is created
from Android by removing Google's bad stuff and making the resulting system work - not trivial).

*Example*
Watch this project: https://soulscircuit.com/
Not production ready yet, but it should be a matter of time only before this happens...



* Linux phones and tablets :noexport:

https://linuxstans.com/linux-phone/

** Murena de-googled

https://murena.com/smartphones/



** PinePhone/Tab

** Librem 5 / Liberty Phone

USA
Lifetime updates
Expensive


** FuriLabs

https://furilabs.com/shop/flx1/


** Volla phone

De-googled Android (?)


https://www.indiegogo.com/projects/volla-tablet-simplify-your-digital-life#/


** CutiePi

https://cutiepi.io/
Started delivering in 2023.
But the deliveries are still stuck now (2025).

** RasPad 3

https://raspad.com/

Looks like no activity for years (since 2021)?

** Waveshare Pi Tablet Kit

https://www.waveshare.com/13.3inch-PiPad-C4.htm


** SunFounder

https://www.sunfounder.com/collections/raspberrypi-kits



** Mtel??? German?


** Resources

https://www.cpdevice.com/best-linux-tablets/

https://liliputing.com/tag/linuxsmartphones/

https://www.tomshardware.com/uk



* Don't throw out your old computer just yet!


As MS Windows 10 is no longer supported, its users are being pressured into upgrading.
But in many cases, it may be that your computer (laptop or desktop) is not suited for running Windows 11.
For example, the computer might not have sufficient RAM memory. Or it may not satisfy whatever funny new hardware requirements that
M$ invents.

What many people don't know is, that it is relatively easy to install a Linux-based system, which in many cases will run absolutely fine.
Check out the Lubuntu Linux system. This system is specially adapted to run well on systems with lower-than-average hardware specs.

Whereas Windows 11 will hardly run in any meaningful way on e.g. a laptop with 4GB RAM, the Lubuntu desktop typically will run great.

Furthermore, Lubuntu (just as any Linux system) is freely available at no cost.

Lubuntu has been around since about 2009, its manual (see link below) is extremely well written and detailed, so that most people - tech savvy or not - will be
able to install it.


[[https://manual.lubuntu.me/lts/][Lubuntu Manual]]

[[https://en.wikipedia.org/wiki/Lubuntu][Lubuntu on Wikipedia]]


* Email service :noexport:

To replace GMail, Outlook, Exchange.

| Provider | Homepage               |
|----------+------------------------|
| Proton   | https://proton.me/mail |
| Posteo   | https://posteo.de/en   |

Others, see https://european-alternatives.eu/category/email-providers


* Application Software                                             :noexport:

** Office
LibreOffice
Note also database...

** Web browser
Vivaldi

** Internet search
Startpage
Ecosia

** Email
Thunderbird


* Replace Microsoft Office with LibreOffice

Unless your usage of MS Office is really complex - using esoteric functionality and/or integrating with other special-purpose software -
switching to LibreOffice should be easy enough. LibreOffice runs on all mainstream operating systems, and then some.

[[https://www.libreoffice.org/][LibreOffice]]

[[https://en.wikipedia.org/wiki/LibreOffice][LibreOffice on Wikipedia]]


* Get rid of Google :noexport:


https://www.computerworld.dk/art/290702/kan-man-overhovedet-droppe-amerikansk-tech-som-iphone-gmail-og-facebook-her-er-de-europaeiske-alternativer?fbclid=IwZXh0bgNhZW0CMTEAAR3Ohx7Xq1-YfKfdYvvUSa1is0TAnG_-ZzXE8d5mbCiiLnzEDxGQrqBOXP4_aem_9OzQpMFoQOIVgm27VvXQpg

https://www.tek.no/nyheter/guide/i/25wQ5r/beste-alternativer-til-amerikanske-tjenester


Every android phone has Google tracking and software crap installed, on a degoogled phone all of Googles tracking software is removed.

And in order to run android apps, on a degoogled phone you need a app called wayDroid that makes the apps that require Google tracking think they are talking to Google severs.


* Smartphones :noexport:

** Extend the life of existing hardware

** Recycle hardware as much as possible

Buy refurbished device.
Optimize the use of the device to minimize the usage of bad software and/or services.

*Example*
Buy a refurbished iPad.
Replace the usage of bad stuff like GMail, Google Drive, Google Photos etc.


** Buy hardware from good sources

*Example*
The FairPhone is mainstream, buy it at a local shop (DK: Proshop).
It's Stock Android, but as always you can replace as much of the Google stuff as you are comfortable with.


** All in - pure hardware and software
As you'd expect, this can be tricky.

*Example*
You like the FairPhone, but you want to get rid of the Google spyware.
Look at Murena.com - they offer the FairPhone with Android replaced by /e/OS (a system that is created
from Android by removing Google's bad stuff and making the resulting system work - not trivial).

*Example*
Watch this project: https://soulscircuit.com/
Not production ready yet, but it should be a matter of time only before this happens...



- Samsung Galaxy
 - Android
 - Designed in South Korea
 - Qualcomm

   
- FairPhone
 - Android
 - Designed in The Netherlands; designed to maximalize sustainability
 - Qualcomm SoC (Qualcomm based in California)

   
- Other
  - Murena
    - /e/OS - this is essentially Android with the Google software removed
    - Murena also offers online services akin to Googles workspaces
    


/e/OS and LineageOS can also be installed on various supported handsets.
To do this yourself can be tricky though (which is why e.g. Murena offers to do it).

  


** Handsets :noexport:

| Name/model       | Company HQ  | OS       | Notes                                                                              | Links                                                     |
|------------------+-------------+----------+------------------------------------------------------------------------------------+-----------------------------------------------------------|
| Samsung Galaxy   | South Korea | Android  |                                                                                    |                                                           |
| FairPhone        | Netherlands | Android  |                                                                                    | https://www.youtube.com/watch?v=Q79Jl842B4g               |
| Murena FreePhone | France      | /e/OS    | Murena offers an online "workspace", with features comparable to Google Workspace. |                                                           |
| Jolla Phone      | Finland     | Sailfish |                                                                                    | https://shop.jolla.com/  - at least one dubious YT review |


** Operating Systems :noexport:

| Name      |   |   |   |   |
|-----------+---+---+---+---|
| Android   |   |   |   |   |
| /e/OS     |   |   |   |   |
| LineageOS |   |   |   |   |
| Sailfish  |   |   |   |   |



** Software :noexport:

| Name      |   |   |   |   |
|-----------+---+---+---+---|
| Android   |   |   |   |   |
| /e/OS     |   |   |   |   |
| LineageOS |   |   |   |   |
| Sailfish  |   |   |   |   |




** Notes  :noexport:

*Installing a FOSS system on an older phone*

Android phones: It seems that if the phone is not too old, then it should be possible to install
a version of LineageOS or /e/OS on it.
If the phone is too old and no longer supported by LineageOS or /e/OS, then the only option may be to
build the new system yourself, which will require substantial technical skill level, so hardly worth it for most people.

https://linuxpusher.dk/vare/linux-mobiltelefon-med-sailfish-os/
offers to install Sailfish OS on an existing, supported phone.



* Tablets :noexport:

| Name/model         | Description    | Pros                 | Cons                                     | Link |
|--------------------+----------------+----------------------+------------------------------------------+------|
| Samsung Galaxy Tab | Various models | South Korean company | Android with Google trappings            |      |
| Murena FreePhone   |                |                      |                                          |      |
| PineTab            |                | Hong Kong            | Hong Kong!, target audience = 

* Online storage :noexport:

To replace Google Drive, Google Photos.

Proton
pCloud

Others see https://european-alternatives.eu/category/file-hosting-services


* Payment services :noexport:

Paypal?


* Investing :noexport:

RPI



* Other Resources

This is a list of resources that might help to get information.

https://isitamerican.eu/
Based on an AI backend, this allows us to check given names of brands/companies for "american-ness".
It may not be 100% reliable, so always be critical and verify things by other sources.

https://european-alternatives.eu/
This is a listing of european alternatives in categories of IT.

https://hudd.no/
Norwegian alternative to Facebook. At this time for norwegians only.

https://zzvibe.com
Danish Facebook alternative.

https://socii.dk/
Brand new danish alternative to Facebook :-)

https://www.youtube.com/watch?v=YaMc64IAC8g
De-googling in general.


* Terms and abbreviations :noexport:

FOSS = Free and Open Source Software



