This is a collection of tips on how to avoid using products from big tech companies residing in areas without a properly functioning democracy.
<<top>>
#+OPTIONS: toc:nil
#+TOC: headlines 3


* Export this document :noexport:

M-x org-md-export-to-markdown RET <filename> RET


* Strategies :noexport:

** Recycle hardware as much as possible

Buy refurbished device.
Optimize the use of the device to minimize the usage of bad software and/or services.

*Example*
Buy a refurbished iPad.
Replace the usage of bad stuff like GMail, Google Drive, Google Photos etc.

** Buy hardware from good sources

*Example*
The FairPhone is mainstream, buy it at a local shop (DK: Proshop).
It's Stock Android, but as always you can replace as much of the Google stuff as you are comfortable with.

** All in - pure hardware and software
As you'd expect, this can be tricky.

*Example*
You like the FairPhone, but you want to get rid of the Google spyware.
Look at Murena.com - they offer the FairPhone with Android replaced by /e/OS (a system that is created
from Android by removing Google's bad stuff and making the resulting system work - not trivial).

*Example*
Watch this project: https://soulscircuit.com/
Not production ready yet, but it should be a matter of time only before this happens...



* Don't throw out your old computer just yet!


As MS Windows 10 is no longer supported, its users are being pressured into upgrading.
But in many cases, it may be that your computer (laptop or desktop) is not suited for running Windows 11.
For example, the computer might not have sufficient RAM memory. Or it may not satisfy whatever funny new hardware requirements that
M$ invents.

What many people don't know is, that it is relatively easy to install a Linux-based system, which in many cases will run absolutely fine.
Check out the Lubuntu Linux system. This system is specially adapted to run well on systems with lower-than-average hardware specs.

Whereas Windows 11 will hardly run in any meaningful way on e.g. a laptop with 4GB RAM, the Lubuntu desktop typically will run great.

Furthermore, Lubuntu (just as any Linux system) is freely available at no cost.

Lubuntu has been around since about 2009, its manual (see link below) is extremely well written and detailed, so that most people - tech savvy or not - will be
able to install it.


[[https://manual.lubuntu.me/lts/][Lubuntu Manual]]

[[https://en.wikipedia.org/wiki/Lubuntu][Lubuntu on Wikipedia]]


* Replace Microsoft Office with LibreOffice

Unless your usage of MS Office is really complex - using esoteric functionality and/or integrating with other special-purpose software -
switching to LibreOffice should be easy enough. LibreOffice runs on all mainstream operating systems, and then some.

[[https://www.libreoffice.org/][LibreOffice]]

[[https://en.wikipedia.org/wiki/LibreOffice][LibreOffice on Wikipedia]]


* Smartphones :noexport:

Installing a FOSS system on an older phone:

Android phones: It seems that if the phone is not too old, then it should be possible to install
a version of LineageOS or /e/OS on it.
If the phone is too old and no longer supported by LineageOS or /e/OS, then the only option may be to
build the new system yourself, which will require substantial technical skill level, so hardly worth it for most people.


| Name/model       | Description | Pros             | Cons          | Link |
|------------------+-------------+------------------+---------------+------|
| FreePhone        |             | European company | Stock Android |      |
| Murena FreePhone |             | European company |               |      |



* Tablets :noexport:

| Name/model         | Description    | Pros                 | Cons                          | Link |
|--------------------+----------------+----------------------+-------------------------------+------|
| Samsung Galaxy Tab | Various models | South Korean company | Android with Google trappings |      |
| Murena FreePhone   |                |                      |                               |      |


* Online storage :noexport:


* Email service :noexport:


* Other Resources

This is a list of resources that might help to get information.

https://isitamerican.eu/
Based on an AI backend, this allows us to check given names of brands/companies for "american-ness".
It may not be 100% reliable, so always be critical and verify things by other sources.

https://european-alternatives.eu/
This is a listing of european alternatives in categories of IT.


* Terms and abbreviations :noexport:

FOSS = Free and Open Source Software



